{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "oops.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "oops.labels" . | nindent 4 }}
  annotations:
    eks.amazonaws.com/role-arn: {{ include "oops.serviceaccount.awsRoleArn" . }}
    {{- with .Values.serviceAccount.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
